apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: app1
  labels:
    app: busybox
spec:
  replicas: 1
  strategy: 
    type: RollingUpdate
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: odise/busybox-curl
        args: ["MESSAGE_BUS"]
        env:
        - name: MESSAGE_BUS
          value: "servicebus-connectionstring@azurekeyvault"
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'echo Container 1 is Running ; sleep 3600']
      serviceAccount: app1sa